<a href="https://colab.research.google.com/github/Prakhar-Pandey28/Scifor_Technologies_Python_Developer_Training/blob/main/Kaggle_TensorFlow_Jul_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [2]:
!pip install kaggle
!pip install tensorflow
!pip install torch torchvision

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [3]:
!kaggle datasets download -d heptapod/titanic

Dataset URL: https://www.kaggle.com/datasets/heptapod/titanic
License(s): DbCL-1.0
  0% 0.00/10.8k [00:00<?, ?B/s]
100% 10.8k/10.8k [00:00<00:00, 18.9MB/s]


In [4]:
import zipfile

with zipfile.ZipFile('titanic.zip', 'r') as zip_ref:
    zip_ref.extractall('titanic')

In [7]:
import pandas as pd
import numpy as np

data = pd.read_csv('titanic/train_and_test2.csv')
print(data.head())

data_numpy = data.to_numpy()
print(np.mean(data_numpy, axis=0))

   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   
3       0  ...        0        0        0       1        0        0       2.0   
4       0  ...        0        0        0       3        0        0       2.0   

   zero.17  zero.18  2urvived  
0        0        0         0 

In [8]:
import tensorflow as tf
import torch

tensor_tf = tf.constant(data_numpy, dtype=tf.float32)
print(tf.reduce_mean(tensor_tf, axis=0))

tensor_torch = torch.tensor(data_numpy, dtype=torch.float32)
print(torch.mean(tensor_torch, dim=0))

tf.Tensor(
[6.5500000e+02 2.9503187e+01 3.3281078e+01 3.5599694e-01 4.9885410e-01
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 3.8502672e-01 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 2.2948816e+00 0.0000000e+00 0.0000000e+00           nan
 0.0000000e+00 0.0000000e+00 2.6126814e-01], shape=(28,), dtype=float32)
tensor([6.5500e+02, 2.9503e+01, 3.3281e+01, 3.5600e-01, 4.9885e-01, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        3.8503e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 2.2949e+00, 0.0000e+00, 0.0000e+00,
               nan, 0.0000e+00, 0.0000e+00, 2.6127e-01])


In [10]:
data_normalized = (data_numpy - np.mean(data_numpy, axis=0)) / np.std(data_numpy, axis=0)
tensor_normalized = tf.constant(data_normalized, dtype=tf.float32)
print(tensor_normalized)

tf.Tensor(
[[-1.7307281  -0.5816283  -0.5032911  ...         nan         nan
  -0.59470254]
 [-1.7280817   0.65865195  0.73474365 ...         nan         nan
   1.6815128 ]
 [-1.7254354  -0.27155825 -0.49024045 ...         nan         nan
   1.6815128 ]
 ...
 [ 1.7254354   0.6974107  -0.5032911  ...         nan         nan
  -0.59470254]
 [ 1.7280817  -0.11652321 -0.48782367 ...         nan         nan
  -0.59470254]
 [ 1.7307281  -0.11652321 -0.21118368 ...         nan         nan
  -0.59470254]], shape=(1309, 28), dtype=float32)


<ipython-input-10-4a1d2933948e>:1: RuntimeWarning: invalid value encountered in divide
  data_normalized = (data_numpy - np.mean(data_numpy, axis=0)) / np.std(data_numpy, axis=0)


In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

features = tensor_normalized[:, :-1]
labels = tensor_normalized[:, -1]

model = Sequential([
    Dense(64, activation='relu', input_shape=(features.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

model.fit(features, labels, epochs=10, batch_size=32)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                1792      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 3905 (15.25 KB)
Trainable params: 3905 (15.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/10
41/41 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.0000e+00
Epoch 2/10
41/41 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0000e+00
Epoch 3/10
41/41 [==============================] - 0s 2ms/step - loss: nan - accuracy: 

In [12]:
predictions = model.predict(features)
print(predictions)

41/41 [==============================] - 0s 2ms/step
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]


In [13]:
data_normalized_torch = (tensor_torch - torch.mean(tensor_torch, dim=0)) / torch.std(tensor_torch, dim=0)
print(data_normalized_torch)

tensor([[-1.7301, -0.5814, -0.5031,  ...,     nan,     nan, -0.5945],
        [-1.7274,  0.6584,  0.7345,  ...,     nan,     nan,  1.6809],
        [-1.7248, -0.2715, -0.4901,  ...,     nan,     nan,  1.6809],
        ...,
        [ 1.7248,  0.6971, -0.5031,  ...,     nan,     nan, -0.5945],
        [ 1.7274, -0.1165, -0.4876,  ...,     nan,     nan, -0.5945],
        [ 1.7301, -0.1165, -0.2111,  ...,     nan,     nan, -0.5945]])


In [15]:
with torch.no_grad():
    predictions_torch = model_torch(features_torch)
print(predictions_torch)

tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]])
